services:
  
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    networks:
      - assignment

  wordpress:
    #image: wordpress:latest
    build:
      context: /wordpress-app # Replace with the path to your directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress-app:/var/www/html
    networks:
      - assignment
    depends_on:
      - db

  go-app:
    build:
      context: /docker-gs-ping  # Replace with the path to your directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - 1190:1190
    restart: always
    environment:
      - GO_APP_HOST=go-app
    networks:
      - assignment
    depends_on:
      - wordpress
  
  nextjs-app:
    build:
      context: /docker-nextjs-app  # Replace with the path to your directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - assignment
    depends_on:
      - go-app


volumes:
  db_data:

networks:
  assignment:
    external: true
