# Use official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY ./docker-nextjs-app/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY ./docker-nextjs-app/. .

# Build the Next.js application
RUN npm run build

# Expose the port Next.js is running on
EXPOSE 1191

# Start the Next.js application
CMD ["npm", "start"]
