name: Build and Push Docker Images (corrected)

# This workflow runs on push events to the main branch
on:
  push:
    branches: [ main ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Navigate to folder and build image
        run: |
          cd ../docker-gs-ping  # Replace with your folder name
          docker build -t v1pul02/go-app:latest .

      - name: Push image
        run: docker push v1pul02/go-app:latest
