name: Build and Push Docker Images (corrected)

# This workflow runs on push events to the main branch
on:
  push:
    branches: [ main ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push go-app image 
        uses: docker/build-push-action@v5  # Uses the official Docker build and push action
        with:
          push: true
          tags: v1pul02/go-app:latest
          # Specify the working directory containing the Dockerfile
          file: ../../Dockerfile-go
      
      - name: Build and push nextjs-app image 
        uses: docker/build-push-action@v5  # Uses the official Docker build and push action
        with:
          push: true
          tags: v1pul02/nextjs-app:latest
          file: ../../Dockerfile-next

      - name: Build and push wordpress-app image 
        uses: docker/build-push-action@v5  # Uses the official Docker build and push action
        with:
          push: true
          tags: v1pul02/wordpress-app:latest
          file: ../../wordpress-app/Dockerfile
    
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop go-app >> /dev/null
            sudo docker rm go-app >> /dev/null
            sudo docker pull v1pul02/go-app:latest
            sudo docker image prune -f
            sudo docker run -d --network assignment -p 1190:1190 --name go-app v1pul02/go-app:latest
      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop nextjs-app >> /dev/null
            sudo docker rm nextjs-app >> /dev/null
            sudo docker pull v1pul02/nextjs-app:latest
            sudo docker image prune -f
            sudo docker run -d --network assignment -p 3000:3000 --name nextjs-app v1pul02/nextjs-app:latest

      - name: Upload folder to server
        uses: appleboy/scp-action@master  # Action for SSH file transfer
        with:
          host: ${{ secrets.HOST }}  # Replace with server hostname
          username: ${{ secrets.USERNAME }}  # Replace with server username
          key: ${{ secrets.KEY }}  # Replace with server password (consider using SSH key for better security)
          port: ${{ secrets.PORT }}
          source: "../../wordpress-app"  # Replace with the path to the folder you want to copy
          target: "/home/vipul/wordpress"  # Replace with the destination folder on the server (including tilde ~ for home directory)
          recursive: true  # Set to true to copy the entire folder structure
      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/vipul/wordpress
            sudo docker compose up --build